# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '*.sln'

  # - task: SonarCloudPrepare@3
  #   displayName: Sonar Prepare
  #   inputs:
  #     SonarQube: 'SonarQube'
  #     organization: 'fachit360'
  #     scannerMode: 'dotnet'
  #     projectKey: 'FachIT360_NetCup-DynDns-Client'
  #     projectName: 'NetCup-DynDns-Client'
