# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  DOCKER_CLI_EXPERIMENTAL: 'true'

steps:
- task: DockerInstaller@0
  displayName: 'Install Docker'
  inputs:
    dockerVersion: '28.1.1'

- task: PowerShell@2
  displayName: 'Set up Docker Buildx and QEMU'
  inputs:
    targetType: inline
    script: |
      docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      docker buildx create --name container --driver docker-container --use
      docker buildx inspect --bootstrap

- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--output $(Build.BinariesDirectory)/$(Build.Repository.Name)'

- task: PowerShell@2
  displayName: 'Get assembly version'
  inputs:
    targetType: 'inline'
    script: |
      $binary = "$(Build.BinariesDirectory)/$(Build.Repository.Name)/netcup-dyndns.dll"
      $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($binary).ProductVersion.Replace('+', '-').Substring(0, 15)
      Write-Host "##vso[task.setvariable variable=dockerTag]$version"

- task: PowerShell@2
  displayName: 'Show Docker tag'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##[debug] $(dockerTag)"

- task: PowerShell@2
  displayName: 'Build multi-arch Docker image'
  inputs:
    targetType: inline
    script: |
      $path="$(Build.BinariesDirectory)/$(Build.Repository.Name)/Dockerfile"
      If (!(Test-Path $path)) { Write-Host "##[debug] Dockerfile not found at $path" } `
      else {Write-Host "##[debug] Dockerfile found at $path"}
      #echo $(docker-password) | docker login -u $(docker-username) --password-stdin registry.fachit360.de
      #docker buildx build -f $(Build.BinariesDirectory)/$(Build.Repository.Name)\NetCup_DynDNS_Client\Dockerfile --platform linux/amd64,linux/arm64 --builder container --push -t registry.fachit360.de/network/fit360-netcup-ddns-client:$(dockerTag) .