# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '9.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--output $(Build.BinariesDirectory)/$(Build.Repository.Name)'

- task: PowerShell@2
  displayName: 'Get assembly version'
  inputs:
    targetType: 'inline'
    script: |
      $binary = "$(Build.BinariesDirectory)/$(Build.Repository.Name)/NetCup-DynDns-Client.dll"
      $version = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($binary).ProductVersion
      Write-Host "##vso[task.setvariable variable=dockerTag]$version"
      
- task: PowerShell@2
  displayName: 'Show docker tag'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##[debug] $(dockerTag)"