<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <UserSecretsId>dotnet-DynDNS_4_NetCup_DotNet-e3309b49-bd15-4a7d-b3ae-9bbf70c6803c</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <AssemblyName>netcup-dyndns</AssemblyName>
        <RootNamespace>FachIT360.Utils.Dns.NetCup</RootNamespace>
        <AssemblyVersion>1.1.13.4116</AssemblyVersion>
        <FileVersion>1.1.13.4116</FileVersion>
        <Version>1.1.13</Version>
        <LangVersion>default</LangVersion>

    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <ShouldCreateLogs>True</ShouldCreateLogs>
        <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
        <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
        <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
        <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
        <UpdatePackageVersion>True</UpdatePackageVersion>
        <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
        <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
        <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
        <PrimaryVersionType>AssemblyVersionAttribute</PrimaryVersionType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <ShouldCreateLogs>True</ShouldCreateLogs>
        <AdvancedSettingsExpanded>True</AdvancedSettingsExpanded>
        <UpdateAssemblyVersion>False</UpdateAssemblyVersion>
        <UpdateAssemblyFileVersion>False</UpdateAssemblyFileVersion>
        <UpdateAssemblyInfoVersion>False</UpdateAssemblyInfoVersion>
        <UpdatePackageVersion>True</UpdatePackageVersion>
        <PackageVersionSettings>AssemblyVersion.IncrementWithAutoReset.None</PackageVersionSettings>
        <AssemblyInfoVersionType>SettingsVersion</AssemblyInfoVersionType>
        <InheritWinAppVersionFrom>None</InheritWinAppVersionFrom>
        <PrimaryVersionType>AssemblyVersionAttribute</PrimaryVersionType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8"/>
        <PackageReference Include="newtonsoft.json" Version="13.0.3" />
    </ItemGroup>
</Project>
